#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build cudy tr3000-v1 128mb ponly 24.10 kernel 6.6 actions.

on:
  workflow_dispatch:
    inputs:
      restore_configuration:
        description: 'Restore configuration archive (ãƒãƒƒã‚¯ã‚¢ãƒƒãƒ—ã—ãŸæ§‹æˆã‚¢ãƒ¼ã‚«ã‚¤ãƒ–ã‚’å¾©å…ƒã™ã‚‹)'
        type: boolean
        default: false
      telegram_notify:
        description: 'Enable Telegram Notify (ãƒ†ãƒ¬ã‚°ãƒ©ãƒ é€šçŸ¥ã‚’æœ‰åŠ¹ã«ã™ã‚‹)'
        type: boolean
        default: false
      upload_firmware:
        description: 'Upload Firmware To Artifact (ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)'
        type: boolean
        default: false
      upload_release:
        description: 'Upload Firmware To Release (ãƒªãƒªãƒ¼ã‚¹ã‚’ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)'
        type: boolean
        default: false
      upload_wenshushu:
        description: 'Upload Firmware To WENSHUSHU (ã‚¦ã‚§ãƒ³ãŠã˜ã•ã‚“ã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)'
        type: boolean
        default: false
  schedule:
    - cron: '0 19 * * 0'

env:
  # immortalwrt 2410
  PONLY2410_K66_REPO_URL: ${{ secrets.PONLY2410_K66_REPO_URL }}
  PONLY2410_K66_REPO_BRANCH: ${{ secrets.PONLY2410_K66_REPO_BRANCH }}
  PONLY2410_K66_REPO_PATCH: ${{ secrets.PONLY2410_K66_REPO_PATCH }}
  # cudy tr3000 v1 modded spi nand 128m
  CD_TR3000_128MB_PONLY2410_K66_HOSTNAME: ${{ secrets.CD_TR3000_128MB_PONLY2410_K66_HOSTNAME }}
  CD_TR3000_128MB_PONLY2410_K66_CONFIG: ${{ secrets.CD_TR3000_128MB_PONLY2410_K66_CONFIG }}
  CD_TR3000_256M_PONLY2410_K66_BACKUP: ${{ secrets.CD_TR3000_256M_PONLY2410_K66_BACKUP }}
  # feeds source
  ADD_FEED_SOURCE: ${{ secrets.ADD_FEED_SOURCE }}
  # diy script
  FIRMWARE_DIY_SCRIPT: ${{ secrets.FIRMWARE_DIY_SCRIPT }}
  # netcore color theme
  ARGON_THEME_CUDY: ${{ secrets.ARGON_THEME_CUDY }}
  # token
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_SHA512SUM: ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_REPACKAGE_SHA512: ${{ secrets.ACCESS_REPACKAGE_SHA512 }}
  # telegram bot
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  # hardware & repo info
  DEVICE_NAME: Cudy-TR3000_v1
  CPU_TAG: mt7981b
  FLASH_TAG: SPI_NAND_128MB
  SOURCE_CODE: padavanonly(237)
  KERNEL_VERSION: kernel_6.6
  OUTPUT_FILENAME: padavanonly-24.10-ryu-mt7981b-cudy_tr3000-v1-128mb-kernel6.6-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: Setup Git Credentials
      run: |
        git config --global url."https://$ACCESS_TOKEN@github.com/0xACE8/".insteadOf "https://github.com/0xACE8/"

    - name: Checkout (ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆ)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Free Disk Space (ãƒãƒ¼ãƒ‰ãƒ‰ãƒ©ã‚¤ãƒ–ã®ç©ºãå®¹é‡ã‚’å¢—ã‚„ã™)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check Server Performance (ã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã‚’ç¢ºèªã™ã‚‹)
      run: |
        echo "âš ï¸è­¦å‘Šã™ã‚‹âš ï¸"
        echo "å‰²ã‚Šå½“ã¦ã‚‰ã‚ŒãŸã‚µãƒ¼ãƒãƒ¼ã®ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«ã¯åˆ¶é™ãŒã‚ã‚Šã¾ã™ã€‚ãƒ—ãƒ©ã‚°ã‚¤ãƒ³ã‚’é¸æŠã—ã™ãã‚‹å ´åˆã¯ã€CPU ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã«æ³¨æ„ã—ã¦ãã ã•ã„ã€‚"
        echo -e "æ—¢çŸ¥ã®CPUãƒ¢ãƒ‡ãƒ«ï¼ˆé™é †ï¼‰: 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "-------------------------CPU æƒ…å ±---------------------------"
        echo "CPUã®ç‰©ç†æ•°  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUã‚³ã‚¢æ•°    : $(nproc)"
        echo -e "CPUãƒ¢ãƒ‡ãƒ«æƒ…å ±:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "------------------------ãƒ¡ãƒ¢ãƒªæƒ…å ±--------------------------"
        echo "ãƒ¡ãƒ¢ãƒªã®è©³ç´°:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "---------------------ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯æƒ…å ±---------------------"
        echo "ãƒãƒ¼ãƒ‰ãƒ‡ã‚£ã‚¹ã‚¯å®¹é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization environment (åˆæœŸåŒ–ç’°å¢ƒ)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq full-upgrade
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code (ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã®ã‚¯ãƒ­ãƒ¼ãƒ³)
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $PONLY2410_K66_REPO_URL -b $PONLY2410_K66_REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        ${{ secrets.ADD_FEED_SOURCE }}

        # Remove All China download sources (ä¸­å›½ã‹ã‚‰ã®ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã‚½ãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Generate Variables (å¤‰æ•°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        SOURCE_REPO="$(echo $PONLY2410_K66_REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV

    - name: Cache Toolchain (ã‚­ãƒ£ãƒƒã‚·ãƒ¥ãƒ„ãƒ¼ãƒ«ãƒã‚§ãƒ¼ãƒ³)
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: MT7981b-${{ env.SOURCE_CODE }}-${{ env.SOURCE_REPO }}-${{ secrets.PONLY2410_K66_REPO_BRANCH }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Updata & install feeds (ã‚¢ãƒƒãƒ—ãƒ‡ãƒ¼ãƒˆã¨ãƒ•ã‚£ãƒ¼ãƒ‰ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«)
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/sbwml/packages_lang_golang -b 25.x feeds/packages/lang/golang
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        ls -la package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom/

    - name: Load custom configuration (ã‚«ã‚¹ã‚¿ãƒ æ§‹æˆã‚’èª­ã¿è¾¼ã‚€)
      run: |
        ${{ secrets.CD_TR3000_128MB_PONLY2410_K66_CONFIG }}
        cat >> .config <<-"EOF"
        CONFIG_PACKAGE_kmod-mtd-rw=y
        EOF
        mv .config openwrt/.config
        cd openwrt
        sed -i 's/gpio-export,output = <1>;/gpio-export,output = <0>;/g' target/linux/mediatek/dts/mt7981b-cudy-tr3000-v1.dtsi
        ${{ secrets.PONLY2410_K66_REPO_PATCH }}
        ${{ secrets.FIRMWARE_DIY_SCRIPT }}
        ${{ secrets.CD_TR3000_128MB_PONLY2410_K66_HOSTNAME }}
        ${{ secrets.ARGON_THEME_CUDY }}
        ls -la package/mtk/drivers/mt_wifi/files/mt7981-default-eeprom/
        
    - name: Restore configuration archive (ãƒãƒƒã‚¯ã‚¢ãƒƒãƒ—ã—ãŸæ§‹æˆã‚¢ãƒ¼ã‚«ã‚¤ãƒ–ã‚’å¾©å…ƒã™ã‚‹)
      if: (github.event.inputs.restore_configuration == 'true' && github.event.inputs.restore_configuration != 'false') || contains(github.event.action, 'restore_configuration') && !cancelled()
      working-directory: ./openwrt
      run: |
        rm -rd files
        ${{ secrets.CD_TR3000_256M_PONLY2410_K66_BACKUP }}

    - name: Boost Wi-Fi 5G signal to 25dbm (Wi-Fi 5Gä¿¡å·ã‚’25dbmã¾ã§ãƒ–ãƒ¼ã‚¹ãƒˆ)
      working-directory: ./openwrt
      run: |
        ${{ secrets.BOOST_5G_TO_25DBM }}

    - name: Download package (ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰)
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware (ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã‚’ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã™ã‚‹)
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upgrading variables (å¤‰æ•°ã®ã‚¢ãƒƒãƒ—ã‚°ãƒ¬ãƒ¼ãƒ‰)
      run: |
        echo "OUTPUT_FILENAME=${OUTPUT_FILENAME}_${FILE_DATE}" >> $GITHUB_ENV

    - name: View Disk Usage (ãƒ‡ã‚£ã‚¹ã‚¯ä½¿ç”¨é‡ã®è¡¨ç¤º)
      if: (!cancelled())
      run: df -hT

    - name: Telegram notify when compilation error (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã‚¨ãƒ©ãƒ¼ãŒç™ºç”Ÿã—ãŸã¨ãã«ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status != 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled()
      env:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âŒ%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã«å¤±æ•—ã—ã¾ã—ãŸï¼%20âŒ%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.FLASH_TAG }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ§¿ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨:%0Aã€€%20ã€€${{ env.KERNEL_VERSION }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ”€ãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»âŒã‚¨ãƒ©ãƒ¼ã®æ™‚é–“:%0Aã€€%20ã€€$(date +'%Yå¹´%mæœˆ%dæ—¥_%Hæ™‚%Måˆ†')%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Organize files (ãƒ•ã‚¡ã‚¤ãƒ«ã‚’æ•´ç†ã™ã‚‹)
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls
        ls | grep -v *sysupgrade.bin | xargs rm -rdf
        mv *.bin ${{ env.OUTPUT_FILENAME }}.bin
        sha512sums -qq -r -P ${{ secrets.ACCESS_SHA512SUM }} sha512sums ${{ env.OUTPUT_FILENAME }}.bin
        ${{ secrets.ACCESS_REPACKAGE_SHA512 }} ${{ env.OUTPUT_FILENAME }}.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Artifact (Artifactã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_firmware == 'true' && github.event.inputs.upload_firmware  != 'false') || contains(github.event.action, 'upload_firmware') && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILENAME }}
        path: ${{ env.FIRMWARE }}

    - name: Telegram notify when compilation complete (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ãŸã‚‰ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled() 
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âœ…%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ã¾ã—ãŸï¼%20âœ…%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.FLASH_TAG }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ§¿ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨:%0Aã€€%20ã€€${{ env.KERNEL_VERSION }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ”€ãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ãƒ•ã‚¡ã‚¤ãƒ«åå‰:%0Aã€€%20ã€€${{ env.OUTPUT_FILENAME}}%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Upload to wenshushu (ã‚¦ã‚§ãƒ³ãŠã˜ã•ã‚“ã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_wenshushu == 'true' && github.event.inputs.upload_wenshushu != 'false') || contains(github.event.action, 'upload_wenshushu') && !cancelled()
      working-directory: ./openwrt
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss -s -p 16 -t 600 --no-progress ${FIRMWARE} 2>&1 | tee wenshushu.log
        WENSHUSHU=$(cat wenshushu.log | grep 'Manage Link:' | cut -d' ' -f3-)
        echo "WENSHUSHU=$WENSHUSHU" >> $GITHUB_ENV

    - name: Telegram notify when compilation complete and upload to wenshushu (ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ãŸã‚‰ãƒ†ãƒ¬ã‚°ãƒ©ãƒ ã‚’ä½¿ç”¨ã—ã¦é€šçŸ¥ã—ã€ã‚¦ã‚§ãƒ³ãŠã˜ã•ã‚“ã«ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_wenshushu == 'true' && github.event.inputs.upload_wenshushu != 'false') || contains(github.event.action, 'upload_wenshushu') && !cancelled()
      working-directory: ./openwrt
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=âœ…%20ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ãŒæˆåŠŸã—ã¾ã—ãŸï¼%20âœ…%0A%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0Aãƒ»ğŸ›œæ”¯æ´ãƒ‡ãƒã‚¤ã‚¹:%0Aã€€%20ã€€${{ env.DEVICE_NAME }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ’½ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯:%0Aã€€%20ã€€${{ env.FLASH_TAG }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ§¿ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨:%0Aã€€%20ã€€${{ env.KERNEL_VERSION }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰:%0Aã€€%20ã€€${{ env.SOURCE_CODE }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“¦ãƒªãƒã‚¸ãƒˆãƒªã‚’:%0Aã€€%20ã€€${{ env.SOURCE_REPO }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ”€ãƒ–ãƒ©ãƒ³ãƒåå‰:%0Aã€€%20ã€€${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ“ãƒ•ã‚¡ã‚¤ãƒ«åå‰:%0Aã€€%20ã€€${{ env.OUTPUT_FILENAME}}%0Aãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼ãƒ¼%0Aãƒ»ğŸ‘²ğŸ»ã‚¦ã‚§ãƒ³ã˜ã•ã‚“:%0Aã€€%20ã€€${{ env.WENSHUSHU }}%0Aï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼%0A"

    - name: Generate Release Tag (ã‚¿ã‚°ã‚’ç”Ÿæˆã™ã‚‹)
      run: |
        RELEASE_TAG="$CPU_TAG-$DEVICE_NAME-$FLASH_TAG-$KERNEL_VERSION-$FILE_DATE"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Upload Firmware To Release (ã‚¢ãƒ¼ãƒ†ã‚£ãƒ•ã‚¡ã‚¯ãƒˆã‚’ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ã™ã‚‹)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_release == 'true' && github.event.inputs.upload_release  != 'false') || contains(github.event.action, 'upload_release') && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.CPU_TAG }}_${{ env.DEVICE_NAME }}_${{ env.FLASH_TAG }}_${{ env.KERNEL_VERSION }}_${{ env.FILE_DATE }}
        allowUpdates: false
        tag: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          **ã“ã®ãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã€CPUã€Œ${{ env.CPU_TAG }}ã€ãƒ¢ãƒ‡ãƒ«ã€Œ${{ env.DEVICE_NAME }}ã€ã‚’æ­è¼‰ã—ãŸãƒ«ãƒ¼ã‚¿ãƒ¼âœ… ${{ env.FLASH_TAG }} âœ…ã«ã®ã¿é©ã—ã¦ã„ã¾ã™ã€‚**
          ### ğŸ“’ã€Œ${{ env.SOURCE_CODE }}ã€ãƒªãƒã‚¸ãƒˆãƒªã®ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‹ã‚‰ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã€‚
          - ğŸ›œ æ”¯æ´ãƒ‡ãƒã‚¤ã‚¹: ${{ env.DEVICE_NAME }}
          - ğŸ’½ ãƒ•ãƒ©ãƒƒã‚·ãƒ¥ã¯: ${{ env.FLASH_TAG }}
          - ğŸ§¿ ã‚«ãƒ¼ãƒãƒ«ä½¿ç”¨: ${{ env.KERNEL_VERSION }}
          - ğŸ“ ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰: ${{ env.SOURCE_CODE }}
          - ğŸ“¦ ãƒªãƒã‚¸ãƒˆãƒªã‚’: ${{ env.SOURCE_REPO }}
          - ğŸ”€ ãƒ–ãƒ©ãƒ³ãƒåå‰: ${{ secrets.PONLY2410_K66_REPO_BRANCH }}
          - ğŸŒ æ¥ç¶šã‚¢ãƒ‰ãƒ¬ã‚¹: 192.168.6.1
          - ğŸ”‘ ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰ã¯: ãªã—
          ### âš ï¸ è­¦å‘Šã™ã‚‹ âš ï¸
          - â€¼ï¸ç¾åœ¨ã®ãƒªãƒã‚¸ãƒˆãƒªã«ã‚ˆã£ã¦ã‚³ãƒ³ãƒ‘ã‚¤ãƒ«ã•ã‚ŒãŸãƒ•ã‚¡ãƒ¼ãƒ ã‚¦ã‚§ã‚¢ã¯ã™ã¹ã¦éå…¬é–‹ã§ã‚«ã‚¹ã‚¿ãƒã‚¤ã‚ºã•ã‚Œã¦ã„ã¾ã™ã€‚
          - â›”ï¸å¼·åˆ¶ãƒ•ãƒ©ãƒƒã‚·ãƒ¥â›”ï¸ã«ã‚ˆã£ã¦ãƒ‡ãƒã‚¤ã‚¹ãŒæå‚·ã—ãŸå ´åˆã€ã“ã®ãƒªãƒã‚¸ãƒˆãƒªã¯ãƒ‡ãƒã‚¤ã‚¹ã®æå‚·ã«ã¤ã„ã¦ä¸€åˆ‡è²¬ä»»ã‚’è² ã„ã¾ã›ã‚“ã€‚

    - name: Delete old workflow runs (å¤ã„ãƒ¯ãƒ¼ã‚¯ãƒ•ãƒ­ãƒ¼å®Ÿè¡Œã‚’å‰Šé™¤ã™ã‚‹)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 3
        keep_minimum_runs: 3

    - name: Delete Old Releases (å¤ã„ãƒªãƒªãƒ¼ã‚¹ã‚’å‰Šé™¤ã™ã‚‹)
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
